services:
  frontend:
    build: .
    ports:
      - "8080:80"
  api:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: npm run api
    ports:
      - "4000:4000"